Algoritmo "semnome"

Var

   idade: inteiro
   salario1, salario2 : real
   nome : caractere


Inicio

    escreval ("digite o seu nome:")
    leia(nome)
    escreva ("Digite a sua idade:")
    leia (idade)
    escreval("digite o valores de dinheiro que ce ganhou")
    leia(salario1)
    leia(salario2)
    
    escreval ("Dados digitados")
    escreval ("Nome = " , nome)
    escreval ("idade = ", idade)
    escreval ("Salario 1 =", salario1)
    escreval ("Salario 2 =", salario2)
Fimalgoritmo