Algoritmo "Pagamento"

Var

   nome: caractere
   valorH, horasT: real
   pagamento: real
Inicio


      escreva("Digite o seu nome: ")
      leia(nome)
      
      escreva("Digite o valor por hora: ")
      leia(valorH)
      
      escreva("Digite as horas trabalhadas: ")
      leia(horasT)
      
      pagamento <- valorH * horasT
      

      
      escreva (" a funcinária ", nome , " recebe " , pagamento)
      
      

 
Fimalgoritmo