Algoritmo "Terreno"

Var

 largura: real
 comprimento: real
 preco: real
 area: real
 metroQuadrado: real
 
    
Inicio
     escreval("qual o tamanho da largura")
     leia(largura)
     escreval("qual o comprimento")
     leia(comprimento)
     escreval(" valor de Metro quadrado")
     leia(metroQuadrado)
     
     area <- largura* comprimento
     escreval("A área é = ", area)
     preco <- area * metroQuadrado
     escreva("O preco é= ", preco)

 
Fimalgoritmo